<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>BatchPad</AssemblyName>
    <RootNamespace>BatchPad.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>BatchPad.App.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <Using Include="System.IO" />
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Templates\**" />
    <EmbeddedResource Include="Templates\new.*" LogicalName="BatchPad.App.Templates.%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BatchPad.Core\BatchPad.Core.csproj" />
  </ItemGroup>

</Project>
